import uuid from "uuid";
import * as dynamoDbLib from "./libs/dynamodb-lib";
import { success, failure } from "./libs/response-lib";

//This Lambda function is to create a new staff to Table Staff,the uuid is generated by system and other details are submited from front end
export async function main(event, context) {
    const data = JSON.parse(event.body);
    const params = {
        TableName: "Staff",
        Item: {
            StaffName: data.StaffName,
            StaffId: uuid.v1(),
            Gender: data.Gender,
            Email: data.Email,
            Skills: data.Skills,
            Birthdate: data.Birthdate,
            StaffIdentity: data.StaffIdentity,
            Pjoin:data.Pjoin
        }
    };

    try {
        await dynamoDbLib.call("put", params);
        return success(params.Item);
    } catch (e) {
        return failure({ status: false });
    }
}