service: ManagmentSystem

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
    createproject:
        handler: create.main
        events:
          - http:
              path: projects
              method: post
              authorizer: aws_iam
              cors: true
    getproject:
        handler: get.main
        events:
          - http:
             path: projects/{id}
             method: get
             authorizer: aws_iam
             cors: true
    listproject:
        handler: list.main
        events:
          - http:
              path: projects
              method: get             
              authorizer: aws_iam
              cors: true
    updateproject:
        handler: update.main
        events:
          - http:
              path: projects/{id}
              method: put
              authorizer: aws_iam
              cors: true
    deleteproject:
        handler: delete.main
        events:
          - http:
              path: projects/{id}
              method: delete
              authorizer: aws_iam
              cors: true
    createUser:
        handler: createUser.main
        events:
          - http:
              path: User
              method: post
              authorizer: aws_iam
              cors: true
    getUser: 
        handler: getUser.main
        events:
          - http:
             path: User/{id}
             method: get
             authorizer: aws_iam
             cors: true
    listUser:
        handler: listUser.main
        events:
          - http:
              path: User
              method: get
              authorizer: aws_iam
              cors: true
    updateUser:
        handler: updateUser.main
        events:
          - http:
              path: User/{id}
              method: put
              authorizer: aws_iam
              cors: true
    deleteUser:
        handler:  deleteUser.main
        events:
          - http:
              path: User/{id}
              method: delete
              authorizer: aws_iam
              cors: true
    PPending:
        handler: PPending.main
        events:
          - http:
              path: Pending
              method: get
              authorizer: aws_iam
              cors: true
    PActive:
        handler: PActive.main
        events:
          - http:
              path: Active
              method: get
              authorizer: aws_iam
              cors: true
    PCompleted:
        handler: PCompleted.main
        events:
          - http:
              path: Completed
              method: get
              authorizer: aws_iam
              cors: true  
    EmailSend:
        handler: Email.main
        events:
          - http:
              path: email
              method: post
              authorizer: aws_iam
              cors: true  
    pSearch:
        handler: pSearch.main
        events:
          - http:
              path: projects/pSearch
              method: get
              authorizer: aws_iam
              cors: true  
    sSearch:
        handler: sSearch.main
        events:
          - http:
              path: sSearch
              method: get
              authorizer: aws_iam
              cors: true  